### PR TITLE
Added a logo for our app, refined collection error handling, fixed order of inputs

### PR DESCRIPTION
**Pull request by cocassel**
Please start the app and check for a cow logo

### CODE REVIEW

**Comment by cocassel** [comment]
I have also adding error handling refinement and bug fixes for the receiver collection page. Please do extensive testing of the collection page and make sure to review the code thoroughly. Make sure to test the following scenarios:
- Leave both both quantity fields blank (both "full" and "empty" weight fields) --> should get errors
- Leave the "full" weight field blank and fill in the "empty" weight field --> should get error
- Leave the "empty" weight field blank and fill in the "full" weight field --> should get error 
- Put a higher number in the "empty" quantity field than in the "full" quantity field --> should get errors
- Fill in correct quantities/weights but have a failed quality test --> pop-up should notify you of failed tests but let you proceed if you want
- Make all quality tests "Pass" but put a higher quantity of milk (full minus empty weights) than the container size (over capacity) --> pop-up should notify you that you are over capacity but should let you proceed if you want
- Make at least one test "Fail" AND put a higher quantity of milk (full minus empty weights) than the container size (over capacity) --> pop-up should notify you that you are over capacity AND have failed test(s) but should let you proceed if you want
- Make all tests "Pass" and put correct/expected quantity values (under container capacity and full > empty) --> pop-up should simply ask you if you want to proceed

If you can think of more scenarios or combinations please test them!!!! Try to break the page!!

**Comment by cocassel** [comment]
ALSO, PLEASE DO NOT MERGE THIS UNTIL ALL OF YOU HAVE REVIEWED IT. We've had lots of bugs on this page so I want verification from all three of you that this is working correctly.

**Comment by cocassel** [comment]
I have also added what I think will fix the automatic prompting of the quantity fields on the collection pages, but I cannot test it myself since I don't have the android phone. @priyankabrodie  could you please test this for me?

**Review by a2dakhqa — COMMENTED** [review]
I have extensively tried to break this and it worked for me

**Comment by priyankabrodie** [comment]
@malvikabalaraj has the android phone

**Review by priyankabrodie — COMMENTED** [review]
Looks good! Tried out all the edge cases and they are working as intended.

**Comment by cocassel** [comment]
I have also added a small fix for the ordering of input on the farmer collection page. Before, when you entered a number in the quantity field, and pressed the enter button, it would automatically open the dropdown but it would keep the keyboard open. Additionally, when you selected an option from the dropdown and pressed enter on the keyboard, nothing would happen (it wouldn't automatically go to the comment field). Now, when you click enter after entering the quantity field, the keyboard closes. The user can then click on the spinner if they so choose. Note that this is not an issue for the receiver collection page since it only three text fields in a row (no spinners).

**Review by malvikabalaraj — APPROVED** [review]
I tested all of the above test cases on the android phone and additional edge cases. Everything looks good!

**Pull request merged**
