### PR TITLE
Various UI changes

### PR DESCRIPTION
**Pull request by priyankabrodie**
**Farmer Search:**

- I resized the buttons at the top of the page (Drop-Off and Reset). I will try to make these look nicer but will finish my other tasks for this sprint first

image

**Farmer Collection:**

- Updated the density test options
- Tried to clean up the UI since text was getting cut off. Please make sure it looks as intended on your emulator

image

Updated the UI of the buttons on the Receiver Login, Guest Transporter Login, Farmer Collection pages:

image

### CODE REVIEW

**Comment by priyankabrodie** [comment]
When 'Forgot Password' is clicked on the Receiver Login, a popup appears telling the user to talk to admin to reset their password

**Review by cocassel — DISMISSED** [review]
I am getting a bug with the density. One of my farmer collection entries had null for density instead of "N/A". This bug might not be caused by this code but let's figure out what's happening before merging

**Comment by cocassel** [comment]
Screen Shot 2020-03-05 at 3 58 25 AM

**Comment by cocassel** [comment]
Okay I see the problem. The java code needs to be updated for this to work.

**Comment by priyankabrodie** [comment]
I think I fixed the density error on the latest commit - please review!

**Review by a2dakhqa — APPROVED** [review]

**Review by a2dakhqa — APPROVED** [review]

**Pull request merged**
