### PR TITLE
4 Bug fixes

### PR DESCRIPTION
**Pull request by cocassel**
Punctuation in the search bar was causing it to crash. I added a fix, which removes all non-letter characters from the search bar. To test this, please do the following:
- Enter a bunch of punctuation into the search bar (e.g. "/.,!''."), which should not do anything
- Enter "Agnes, Abuga" into the search bar. This should find the farmer "Agnes Abuga"

I have also removed leading and trailing spaces as well as turning multiple spaces into single spaces. To test this please enter "    Anges   Abuga   " into the search bar. This should still find "Agnes Abuga"

To test the above two changes together please enter "   ag*@ne.s,   ./ab''ug.a.     " into the search bar. You should still be able to see "Agnes Abuga" in the results.

Please do some other tests too!

### CODE REVIEW

**Comment by cocassel** [comment]
I also fixed a bug for the receiver login page. Apostrophes in the username field were causing the app to crash. To test this fix, please put an apostrophe in the username field and try to log in. You should see the invalid credentials pop-up. The app should not crash.

**Comment by cocassel** [comment]
I also fixed a bug that happened with the comment field on both the farmer collection and receiver collection pages. If commas were inputted in the comment field, it was causing the resulting CSVs to be messed up. Since CSVs are comma separated, we need to make sure there are no commas anywhere in our data. I fixed this by simply removing commas from the inputted text in the comment field. I have also converted the whole insert statement for both farmer and receiver collection to use content values because this method better handles other punctuation like apostrophes. Please do some tests with both collection pages and make sure to put lots of punctuation (specifically commas) in the comment fields. Make sure the exported CSVs are as expected.

**Comment by cocassel** [comment]
I also got rid of punctuation in the guest transporter name field. Please try putting punctuation in the field. It should be taken out. Only letters should remain.

**Review by malvikabalaraj — COMMENTED** [review]
Looks good! I tested the above scenarios (and additional scenarios) and took a look at the code

**Comment by priyankabrodie** [comment]
Reviewed all bug fixes, looks good!

**Review by malvikabalaraj — APPROVED** [review]
Looks good!

**Pull request merged**
