### PR TITLE
Fixed UI on Farmer and Receiver Collection Pages

### PR DESCRIPTION
**Pull request by priyankabrodie**
On smaller devices such as the Nexus One, the titles on the collection pages were getting cut off. 

I found the container dropdown on the farmer collection page to affect the titles so I moved the dropdown to its own line. 

Please test the collection pages on smaller devices (i.e. Nexus One) and make sure all text is visible.

### CODE REVIEW

**Comment by cocassel** [comment]
I don't see the little arrow on my nexus one. I think maybe it's getting cut off
Screen Shot 2020-03-17 at 7 19 07 PM

**Comment by priyankabrodie** [comment]
@cocassel can you check if you can see the arrow now?

**Comment by cocassel** [comment]
Looks good to me, but perhaps we could make a little bit more room so "(L)" could be on the same line (on both transporter and receiver collection)?
Screen Shot 2020-03-19 at 9 14 49 PM

**Comment by cocassel** [comment]
@priyankabrodie what do you think about my idea?

**Review by cocassel — APPROVED** [review]

**Pull request merged**
