### PR TITLE
Transporter homepage

### PR DESCRIPTION
**Pull request by a2dakhqa**
Transporter login: clicking on on one of the list view leads to transporter homepage (empty currently). additionally a toast should be present at the bottom of the screen for the selected button the list.

### CODE REVIEW

**Comment by cocassel** [comment]
I see "transporter homepage" on the new activity but it's not centered. Does it look like that for you?

**Comment by a2dakhqa** [comment]
fixed the centering issue

**Comment by malvikabalaraj** [comment]
Looks good to me!

**Review by malvikabalaraj — APPROVED** [review]
Looks good!

**Pull request merged**
